# Generated by Django 3.2 on 2023-04-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=254)),
                ('hash', models.CharField(max_length=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
